after clicking sign up after entering name and email as a coach Console Error
FirebaseError: Missing or insufficient permissions. user shows in authentificationand does now show in database